'use strict';
const $=id=>document.getElementById(id);
const messages={en:{subtitle:'A little imagination. A lot of physics.',eyebrow:'YOUR PHYSICS PLAYGROUND',title:'Draw it. Watch it come alive.',reset:'↺ Reset scene',pause:'Ⅱ Pause',play:'▶ Play',tools:'Drawing tools',pen:'Freehand',line:'Line',box:'Rectangle',circle:'Circle',move:'Grab',erase:'Erase',body:'New objects',fixed:'Fixed in place',fixedHelp:'Turn on to build ramps and platforms.',color:'Color',gravity:'Gravity',bounce:'Bounciness',undo:'↶ Undo last drawing',clear:'Clear canvas',objects:'objects',canvaslabel:'IMAGINATION HAS GRAVITY.',shortcut:'Space to pause · Ctrl / ⌘ Z to undo',footer:'Made to experiment. No rules, just physics.',touch:'Mouse, pen & touch ready',running:'Simulation running',paused:'Simulation paused',hint:'Draw a line or shape anywhere on the canvas.',moveHint:'Drag an object to move it. Release to let it fall.',eraseHint:'Tap an object to remove it.',limit:'Canvas full. Erase some objects to keep drawing.',empty:'Canvas cleared. Draw something new.',missing:'The physics engine could not load. Keep the vendor folder beside index.html.'},ar:{subtitle:'قليل من الخيال. كثير من الفيزياء.',eyebrow:'مساحتك لتجربة الفيزياء',title:'ارسم فكرتك. وشاهدها تتحرك.',reset:'↺ إعادة المشهد',pause:'Ⅱ إيقاف مؤقت',play:'▶ تشغيل',tools:'أدوات الرسم',pen:'رسم حر',line:'خط',box:'مستطيل',circle:'دائرة',move:'تحريك',erase:'مسح',body:'الأجسام الجديدة',fixed:'ثابت في مكانه',fixedHelp:'فعّل هذا الخيار لبناء المنحدرات والمنصات.',color:'اللون',gravity:'الجاذبية',bounce:'الارتداد',undo:'↶ تراجع عن آخر رسم',clear:'مسح اللوحة',objects:'أجسام',canvaslabel:'للخيال جاذبية.',shortcut:'مسافة للإيقاف · Ctrl / ⌘ Z للتراجع',footer:'مساحة للتجربة. أنت ترسم والفيزياء تتكفل بالباقي.',touch:'يدعم الماوس والقلم واللمس',running:'المحاكاة تعمل',paused:'المحاكاة متوقفة',hint:'ارسم خطًا أو شكلًا في أي مكان على اللوحة.',moveHint:'اسحب الجسم لتحريكه، ثم اتركه ليسقط.',eraseHint:'اضغط على الجسم لمسحه.',limit:'اللوحة ممتلئة. امسح بعض الأجسام لمتابعة الرسم.',empty:'تم مسح اللوحة. ارسم فكرة جديدة.',missing:'تعذر تحميل محرك الفيزياء. أبقِ مجلد vendor بجانب index.html.'}};
let lang='en',paused=false,tool='pen';try{lang=localStorage.getItem('graphics-box-language')==='ar'?'ar':'en'}catch{}
function translate(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.querySelectorAll('[data-i]').forEach(e=>e.textContent=messages[lang][e.dataset.i]);$('language').textContent=lang==='en'?'العربية':'English';$('play').textContent=messages[lang][paused?'play':'pause'];$('state').textContent=messages[lang][paused?'paused':'running'];$('hint').textContent=messages[lang][tool==='move'?'moveHint':tool==='erase'?'eraseHint':'hint'];$('canvas').setAttribute('aria-label',lang==='ar'?'لوحة رسم ومحاكاة الفيزياء':'Physics drawing canvas');$('gravity').setAttribute('aria-label',messages[lang].gravity);$('bounce').setAttribute('aria-label',messages[lang].bounce)}
$('language').onclick=()=>{lang=lang==='en'?'ar':'en';try{localStorage.setItem('graphics-box-language',lang)}catch{}translate()};translate();
if(!window.Matter){$('notice').textContent=messages[lang].missing;throw Error('Matter.js missing')}
const {Engine,Bodies,Body,Composite,Constraint,Query,Vector}=Matter,engine=Engine.create({enableSleeping:true}),canvas=$('canvas'),ctx=canvas.getContext('2d');
const W=1000,H=650;let objects=[],walls=[],gesture=null,grab=null,pointer=null;const colors=['#ac9cff','#baff8b','#ffb97a','#82ccf9'];let colorIndex=0;
function opts(fixed=false,color=$('color').value){return {isStatic:fixed,restitution:+$('bounce').value,friction:.45,frictionAir:.006,render:{fillStyle:color},plugin:{color}}}
function add(body){if(objects.length>=150){$('notice').textContent=messages[lang].limit;return}objects.push(body);Composite.add(engine.world,body);$('count').textContent=objects.length;return body}
function remove(body){Composite.remove(engine.world,body);objects=objects.filter(b=>b!==body);$('count').textContent=objects.length}
function release(){if(grab){Composite.remove(engine.world,grab);grab=null}gesture=null;pointer=null}
function clear(){release();Composite.clear(engine.world,false);Engine.clear(engine);objects=[];walls=[Bodies.rectangle(W/2,H+25,W+100,50,{isStatic:true}),Bodies.rectangle(-25,H/2,50,H*4,{isStatic:true}),Bodies.rectangle(W+25,H/2,50,H*4,{isStatic:true})];Composite.add(engine.world,walls);$('count').textContent='0'}
function demo(){clear();add(Bodies.rectangle(250,300,340,18,{...opts(true,'#72809c'),angle:.22}));add(Bodies.rectangle(735,450,330,18,{...opts(true,'#72809c'),angle:-.22}));add(Bodies.rectangle(490,602,160,18,opts(true,'#72809c')));add(Bodies.circle(180,140,36,opts(false,'#ac9cff')));add(Bodies.rectangle(340,145,68,68,{...opts(false,'#baff8b'),angle:.25}));add(Bodies.polygon(720,220,3,52,opts(false,'#ffb97a')));add(Bodies.circle(830,160,23,opts(false,'#82ccf9')))}
function view(){const r=canvas.getBoundingClientRect(),s=Math.min(r.width/W,r.height/H);return {r,s,x:(r.width-W*s)/2,y:(r.height-H*s)/2}}
function point(e){const {r,s,x,y}=view();return {x:Math.max(0,Math.min(W,(e.clientX-r.left-x)/s)),y:Math.max(0,Math.min(H,(e.clientY-r.top-y)/s))}}
function hit(p){return Query.point(objects,p).at(-1)}
canvas.onpointerdown=e=>{if(pointer!==null)return;e.preventDefault();pointer=e.pointerId;canvas.setPointerCapture(pointer);const p=point(e);$('notice').textContent='';if(tool==='erase'){const b=hit(p);if(b)remove(b);return}if(tool==='move'){const b=hit(p);if(b){gesture={body:b,last:p};if(!paused&&!b.isStatic){Matter.Sleeping.set(b,false);grab=Constraint.create({pointA:p,bodyB:b,pointB:Vector.sub(p,b.position),length:0,stiffness:.15,damping:.1});Composite.add(engine.world,grab)}}return}gesture={points:[p],end:p,kind:tool,fixed:$('static').checked,color:$('color').value}};
canvas.onpointermove=e=>{if(e.pointerId!==pointer||!gesture)return;const p=point(e);if(gesture.body){if(grab)grab.pointA=p;else{Body.translate(gesture.body,Vector.sub(p,gesture.last));Body.setVelocity(gesture.body,{x:0,y:0})}gesture.last=p;return}gesture.end=p;const last=gesture.points.at(-1);if(gesture.kind==='pen'&&Vector.magnitude(Vector.sub(p,last))>8&&gesture.points.length<90)gesture.points.push(p)};
function segment(a,b,o){const d=Vector.sub(b,a),len=Vector.magnitude(d);return Bodies.rectangle((a.x+b.x)/2,(a.y+b.y)/2,Math.max(len,2)+3,9,{...o,angle:Math.atan2(d.y,d.x)})}
canvas.onpointerup=e=>{if(e.pointerId!==pointer)return;if(gesture&&!gesture.body){const g=gesture,a=g.points[0],b=g.end,o=opts(g.fixed,g.color);let body;if(g.kind==='circle'){const radius=Math.min(220,Vector.magnitude(Vector.sub(b,a)));if(radius>4)body=Bodies.circle(a.x,a.y,radius,o)}else if(g.kind==='box'){const w=Math.abs(b.x-a.x),h=Math.abs(b.y-a.y);if(w>5&&h>5)body=Bodies.rectangle((a.x+b.x)/2,(a.y+b.y)/2,w,h,o)}else if(g.kind==='line'){if(Vector.magnitude(Vector.sub(b,a))>5)body=segment(a,b,o)}else{if(Vector.magnitude(Vector.sub(g.points.at(-1),b))>2)g.points.push(b);if(g.points.length>1){const parts=g.points.slice(1).map((p,i)=>segment(g.points[i],p,{...o,isStatic:false}));body=Body.create({...o,isStatic:false,parts});if(g.fixed)Body.setStatic(body,true)}}if(body)add(body)}release()};canvas.onpointercancel=release;canvas.onlostpointercapture=release;
document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{release();tool=b.dataset.tool;document.querySelectorAll('[data-tool]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b?'true':'false')});canvas.style.cursor=tool==='move'?'grab':tool==='erase'?'pointer':'crosshair';translate()});
$('play').onclick=()=>{release();paused=!paused;translate()};$('reset').onclick=()=>{paused=false;demo();translate();$('notice').textContent=''};$('undo').onclick=()=>{release();if(objects.length)remove(objects.at(-1))};$('clear').onclick=()=>{clear();$('notice').textContent=messages[lang].empty};$('gravity').oninput=e=>{engine.gravity.y=+e.target.value;$('gv').textContent=(+e.target.value).toFixed(1)+'×';objects.forEach(b=>Matter.Sleeping.set(b,false))};$('bounce').oninput=e=>$('bv').textContent=Math.round(+e.target.value*100)+'%';
document.addEventListener('keydown',e=>{if(/INPUT|BUTTON|TEXTAREA|SELECT/.test(e.target.tagName))return;if(e.code==='Space'){e.preventDefault();$('play').click()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();$('undo').click()}});
function drawBody(b){const parts=b.parts.length>1?b.parts.slice(1):[b];ctx.fillStyle=b.plugin.color||'#ac9cff';ctx.strokeStyle=b.isStatic?'#adb9d0':ctx.fillStyle;ctx.lineWidth=1.6;parts.forEach(p=>{ctx.beginPath();if(p.circleRadius)ctx.arc(p.position.x,p.position.y,p.circleRadius,0,Math.PI*2);else{p.vertices.forEach((v,i)=>i?ctx.lineTo(v.x,v.y):ctx.moveTo(v.x,v.y));ctx.closePath()}ctx.globalAlpha=b.isStatic?.65:.85;ctx.fill();ctx.globalAlpha=1;ctx.stroke()});if(b.circleRadius){ctx.beginPath();ctx.moveTo(b.position.x,b.position.y);ctx.lineTo(b.position.x+Math.cos(b.angle)*b.circleRadius*.65,b.position.y+Math.sin(b.angle)*b.circleRadius*.65);ctx.strokeStyle='#263149';ctx.lineWidth=2;ctx.stroke()}}
let last=0,acc=0;function frame(now){const dt=Math.min(50,now-last||16.67);last=now;if(!paused&&!document.hidden){acc+=dt;while(acc>=1000/60){Engine.update(engine,1000/60);acc-=1000/60}}else acc=0;const {r,s,x,y}=view(),dpr=Math.min(devicePixelRatio||1,2),cw=Math.round(r.width*dpr),ch=Math.round(r.height*dpr);if(canvas.width!==cw||canvas.height!==ch){canvas.width=cw;canvas.height=ch}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,r.width,r.height);ctx.translate(x,y);ctx.scale(s,s);ctx.strokeStyle='#536178';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,H-1);ctx.lineTo(W,H-1);ctx.stroke();objects.forEach(drawBody);if(gesture&&!gesture.body){const g=gesture,a=g.points[0],b=g.end;ctx.strokeStyle=g.color;ctx.lineWidth=4;ctx.setLineDash([8,5]);ctx.beginPath();if(g.kind==='circle')ctx.arc(a.x,a.y,Math.min(220,Vector.magnitude(Vector.sub(b,a))),0,Math.PI*2);else if(g.kind==='box')ctx.rect(a.x,a.y,b.x-a.x,b.y-a.y);else{ctx.moveTo(a.x,a.y);if(g.kind==='pen')g.points.forEach(p=>ctx.lineTo(p.x,p.y));ctx.lineTo(b.x,b.y)}ctx.stroke();ctx.setLineDash([])}requestAnimationFrame(frame)}demo();requestAnimationFrame(frame);
